COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

MAKEOPTS="-j12 -l12"
LLVM_TARGETS="X86 AMDGPU"

L10N="en en-US"
ACCEPT_LICENSE="-* @FREE"

USE="
  X wayland
  pipewire pulseaudio
  bluetooth
  udev policykit
  ssl
  btrfs zstd lz4
  elogind
  threads
  modules-sign secureboot dist-kernel
  bash-completion zsh-completion
"

VIDEO_CARDS="amdgpu radeonsi"
INPUT_DEVICES="libinput"

GENTOO_MIRRORS="https://linux.ruhr-uni-bochum.de/gentoo-mirror/"

PKGDIR="/var/cache/binpkgs"
PORTAGE_TMPDIR="/var/tmp"

FEATURES="
  userfetch usersync
  parallel-fetch parallel-install
  xattr
  ipc-sandbox network-sandbox pid-sandbox usersandbox
  strict
  buildpkg
"

PORTAGE_ELOG_CLASSES="info log qa rawwarn warn error"
PORTAGE_ELOG_SYSTEM="save"
PORTAGE_NICENESS="5"
PORTAGE_IONICE_COMMAND="/usr/bin/ionice -c3 -p \${PID}"

EMERGE_DEFAULT_OPTS="
  --ask
  --verbose
  --with-bdeps=y
  --complete-graph=y
  --jobs=6
  --load-average=12
  --quiet-build=n
  --autounmask-continue
  --binpkg-respect-use=y
"

LC_MESSAGES=C.utf8

## Secureboot
MODULES_SIGN_KEY="/root/kernel_key.pem"
MODULES_SIGN_HASH="sha512"
SECUREBOOT_SIGN_KEY="/root/kernel_key.pem"
SECUREBOOT_SIGN_CERT="/root/kernel_key.pem"
GRUB_PLATFORMS="efi-64"
