#+TITLE: Tmux Configuration
#+AUTHOR: DrDos
#+DATE: 2025-07-15
#+LANGUAGE: en
#+OPTIONS:     toc:nil
#+PROPERTY:    header-args :eval never-export

This is the directory for Tmux Configuration. I use the Tmux Plugin Manager (TPM) as well as some plugins. I made this conf to don't interfere with Emacs, and to enable emacs-like behaviour in Tmux.

Have fun!

* Changes
- Better design and modeline
- Behavioral improvements
- Convenience features like mouse support and a few plugins
- Key changes:
| Function                 | New key                 |
|--------------------------+-------------------------|
| prefix                   | =C-g=                   |
| split vertical           | =v=                     |
| split horizontal         | =h=                     |
| reload config            | =C-g r=                 |
| navigate panes ←/→/↑/↓ | =C-b / C-f / C-p / C-n= |
  
* Setup
** General
Just place the file in =~/.config/tmux/tmux.conf=. Tmux will recognize it automatically. You can of course put it somewhere else. However, please note that some paths in the file are hard-coded, so change them accordingly.
** TPM
#+begin_src bash
  mkdir -p ~/.config/tmux/plugins
  git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tp
#+end_src
Then: Open Tmux and install plugins with =prefix + I=.

** Errors
*** TPM returns 1
This is an issue related to tmux-mem-cpu-load. Install cmake to fix it or disable the plugin. Issue: https://github.com/thewtex/tmux-mem-cpu-load/issues/55

*** Tmux does not recognize the config file
Check your =$XDG_CONFIG_HOME=.

