#+TITLE: Emacs Configuration Files
#+AUTHOR: DrDos
#+DATE: 2025-07-16
#+LANGUAGE: en
#+OPTIONS: toc:nil
#+PROPERTY: header-args :eval never-export

This is the directory with my emacs configuration files.
Location: =emacs/init.el= → symlink to =~/.config/emacs/init.el=

* Highlights
- Solarized‑Light theme with Doom‑modeline
- Tree‑sitter, Eglot, Flycheck and various major-modes for programming
- which‑key, Magit, Company, Yasnippet
- Org‑mode improvements like better headings
- various other stuff
  
* Setup
** Required packages for full functionality
There are some system packages that are integrated into this config. For the complete list, please see the comments at the beginning of the document.
Maybe I forgot to update this list, the document itself will always be up to date.

- A nerd font available on the system
- Linters you need (currently ansible-lint, pylint, eslint configured)
- Language-support-packages (currently cmake, clang-tidy, tidy, devscripts (debian))

Notice that the nerd font is hard coded in the file, so if you use another one then change the reference accordingly.
** General
#+begin_src bash
  git clone https://github.com/therealdrdos/dotfiles ~/Somewhereonyourmachine
  cp Somewhereonyourmachine/dotfiles/emacs/init.el ~/.config/emacs
  emacs
#+end_src
First start triggers MELPA package installation and initial setup.

** Errors
*** Treesitter Files missing
You need to fetch the current files. Run:
#+begin_src emacs-lisp
M-x treesit-install-language-grammar RET YourDesiredLanguage RET
#+end_src
*** Emacs does not recognize the config file
Check your =$XDG_CONFIG_HOME=.
