---
name: Commit-lint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/commit-lint.yaml'
      - 'commitlint.config.mjs'
      - '**'

jobs:
  commit-lint:
    name: Validate commit messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs
